Anime-Game-Servers/Grasscutter-Quests

src/main/java/emu/grasscutter/game/quest/GameMainQuest.java, src/main/java/emu/grasscutter/game/quest/GameQuest.java, src/main/java/emu/grasscutter/game/quest/QuestManager.java
Auto finish all hidden child quests when finishing the main quest, QuestListUpdateNotify queue deprecated because if no event triggers = no packets to client with PacketQuestListUpdateNotify (in case of manual finish quest by id)
Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
=> Auto finish all hidden child quests + QuestListUpdateNotify queue deprecated

src/main/java/emu/grasscutter/scripts/SceneScriptManager.java, src/main/java/emu/grasscutter/scripts/ScriptLib.java
- Mimic the original pos usage of group loading
- Revert PrintContextLog related to debug mode
=> Add group loading based on pos to mimic the original behaviour

src/main/java/emu/grasscutter/scripts/SceneScriptManager.java, src/main/java/emu/grasscutter/scripts/ScriptLib.java, src/main/java/emu/grasscutter/scripts/data/controller/EntityController.java, src/main/java/emu/grasscutter/server/packet/recv/HandlerExecuteGadgetLuaReq.java
With this commit i solve a bug that doesn't take account what type of variables are refreshed to default value or not.
And this solves the gather points not showing the actual gather status on client. This is done at the same time of the update of the custom resources
=> Fix variable refreshing and add GetGatherConfigIdList

src/main/java/emu/grasscutter/game/quest/conditions/ConditionStateEqual.java, src/main/java/emu/grasscutter/game/quest/conditions/ConditionStateNotEqual.java, src/main/java/emu/grasscutter/game/quest/content/ContentQuestStateEqual.java, src/main/java/emu/grasscutter/game/quest/content/ContentQuestStateNotEqual.java, src/main/java/emu/grasscutter/game/world/WorldDataSystem.java, src/main/java/emu/grasscutter/server/packet/recv/HandlerClientScriptEventNotify.java, src/main/java/emu/grasscutter/server/packet/send/PacketGetSceneAreaRsp.java, src/main/java/emu/grasscutter/server/packet/send/PacketGetScenePointRsp.java
* Fixed quest content/cond checks checking for unstarted quests (thx @scooterboo )
* Add the actual cfg id to client send EVENT_AVATAR_NEAR_PLATFORM events (thx @scooterboo )
* Actually send the unlocked areas from the player instead of a brute forced list
* Use city data to generate the city list in GetSceneAreaRsp, instead of a hard coded list
* Catch null positions in WorldDataSystems getInvestigationMonster
=> Small fixes

src/main/java/emu/grasscutter/game/entity/gadget/platform/BaseRoute.java
Quaternions should NOT be treated like Euler angles
Platform at the end of Chasing Shadows has correct rotation.
=> Fix Quaternions

src/main/java/emu/grasscutter/data/excels/ChapterData.java
At the start of the last quest in an act, a banner would appear saying that you *started* the act:
There was a typo in ChapterData.java where endQuestChapterMap was incorrectly beginQuestChapterMap.
This is fix already in main grasscutter, but the history is gone.
With the corrections:
Works great!
=> Fix typo in ChapterData.java

src/main/java/emu/grasscutter/game/entity/EntityRegion.java
While debugging a different problem, I noticed that the Avatar was leaving every region every refresh tick.
Before:
https://github.com/Anime-Game-Servers/Grasscutter-Quests/assets/1877986/3a2656fe-8eda-4782-acca-ca8a0be38599
I found that leftEntities was not being cleared like newEntities. I looked at resetNewEntities and added the symmetric code to resetEntityLeave.
After:
https://github.com/Anime-Game-Servers/Grasscutter-Quests/assets/1877986/19ac71ca-156d-4286-86c4-e03fe0f66e61
=> Fix bug with region leave not resetting properly

src/main/java/emu/grasscutter/scripts/SceneScriptManager.java
In SceneScriptManager.refreshGroup:
groudId -> groupId
Also removed some old, inaccurate info about regions.
=> Update typo in SceneScriptManager.java

src/main/java/emu/grasscutter/database/DatabaseHelper.java
At the end of An Impromptu Change of Plan, only one of the three Adepti quests fired: Wangshu
When Wangshu saves, the timing on my computer makes it save two times at the same time (for 100301 and 100320).
When this happens, a `E11000 duplicate key error collection: grasscutter.quests index: _id_ dup key: { _id: ObjectId('65ceb86e3a88695a7c17d491') }` is thrown, and the quest accept system bails. The quest system ends up not accepting the other two Adepti quests.
A long term fix would be for the main quest to not save to the backup database as things change, but to save in batches. For example on world ticks or every 30s worth of world ticks.
This proposed fix makes it gracefully fail and continue to accept quests if saving fails.
=> Handle concurrent saving error

src/main/java/emu/grasscutter/scripts/ScriptLibHandler.java
When interacting with Ley Line Outcrops, a `Defeat all opponents  0/7` notif appears, but defeating all of the enemies does nothing.
I quickly found that unimplemented ScriptLibHander.AddBlossomScheduleProgressByGroupId was being called every time a monster was defeated and that BlossomManager had a unused function addBlossomProgress with the note: `Update Blossom camp's progress (on monster die for example), triggered by ScriptLib`. I noticed by looking at the lua that if only a EVENT_BLOSSOM_PROGRESS_FINISH was called, the group's sequence could continue. addBlossomProgress has a EVENT_BLOSSOM_PROGRESS_FINISH in it. I'm pretty sure linking these up is the right thing to do.
After linking them up, progress happened correctly!
=> link AddBlossomScheduleProgressByGroupId to addBlossomProgress

src/main/java/emu/grasscutter/game/quest/QuestManager.java, src/main/java/emu/grasscutter/server/packet/send/PacketQuestGlobalVarNotify.java
Can you believe it? We're living in the future now. A future where quests can QUEST_EXEC_SET_QUEST_GLOBAL_VAR in harmony.
102305 (Heart of Glaze) uses a QUEST_EXEC_SET_QUEST_GLOBAL_VAR to set 10009 to 1. This starts quest 102401 (Turning Point).
Without PacketQuestGlobalVarNotify, the client isn't notified that the global variable changed. You are left standing in Golden House at the end of the Childe battle.
Code was downstreamed from Grasscutter. That's why it looks so ＲＥＡＤＡＢＬＥ.
m1024: Turning Point can start and also fail/rollback correctly.
=> Downstream PacketQuestGlobalVarNotify

src/main/java/emu/grasscutter/scripts/SceneScriptManager.java
Was trying to trigger Boreas, but ran into problems with his pre-battle timer not being created. (group 133002259).
There's some more traditional pyro monuments close by with the same issue (group 133002344)
The old code has several flaws:
* If the EVENT_TIMER_EVENT has source = "", the timer never gets created.
* If multiple EVENT_TIMER_EVENT match the source (like if you made the code check if trigger.getSource().equals("")), the timer is canceled and created over and over on each iteration that matches. Only the last timer remains.
* All of it doesn't matter anyway since the callEvent in realCallEvent (line 725 or so) is going to handle the EVENT_TIMER_EVENT for every timer trigger where the source matches the source or the source is "".
Iteration and source checking does not make …
=> Have timers trigger by events with source = ""

src/main/java/emu/grasscutter/game/ability/actions/ActionLoseHP.java
In dungeon 1114 (scene 20104), when the floor in front of the statue is activated (/entity 3014 state201), the player's health becomes NaN: 
This is because part of the damage equation uses the floor's current HP, which is Infinite. We set the current HP of invincible objects to Positive infinity when they are created.
amountByCasterCurrentHPRatio is zero, FIGHT_PROP_CUR_HP is Infinity.
Multiplying zero by Infinity results in NaN. Adding anything to NaN is NaN
=> Update ActionLoseHP.java to ignore Infinite CUR_HP

src/main/java/emu/grasscutter/game/quest/GameMainQuest.java, src/main/java/emu/grasscutter/game/quest/GameQuest.java, src/main/java/emu/grasscutter/game/quest/QuestManager.java, src/main/java/emu/grasscutter/game/quest/exec/ExecRollbackParentQuest.java
This is a WIP for changes to the rewind system.
Fixes problems I had rewinding this quest in https://github.com/Anime-Game-Servers/Grasscutter-Quests/issues/104 in 1009xx:
and this one in 1021xx:
The original code very much looked like it thought it would be green up to one orange quest, and then red thereafter.
This new code will roll back to the first green/orange quest that's a valid rollback quest. Previously it would roll back to the first orange quest.
This new code will execute all BeginExec on a login.
https://github.com/Anime-Game-Servers/Grasscutter-Quests/issues/104
=> Rewind Changes

src/main/java/emu/grasscutter/server/game/GameSession.java, src/main/java/emu/grasscutter/server/packet/recv/HandlerPlayerForceExitReq.java, src/main/java/emu/grasscutter/server/packet/recv/HandlerPlayerLoginReq.java, src/main/java/emu/grasscutter/server/packet/recv/HandlerPlayerQuitDungeonReq.java, src/main/java/emu/grasscutter/server/packet/recv/HandlerQuickUseWidgetReq.java, src/main/java/emu/grasscutter/server/packet/recv/HandlerSceneInitFinishReq.java, src/main/java/emu/grasscutter/server/packet/recv/HandlerSetEntityClientDataNotify.java, src/main/java/emu/grasscutter/server/packet/recv/HandlerSetPlayerBornDataReq.java
Replace
session.send(new BasePacket(PacketOpcodes.Packet)); 
with
session.send(new BasePacket(session.getPackageIdProvider().getPacketId("Packet")));
=> Replace PacketOpcodes references with strings

src/main/java/emu/grasscutter/data/excels/WorldAreaData.java
Going to a Statue of the seven and choosing "Resonate with {X}" wouldn't result in any changes.
worldAreaDataMap was empty!
My resources have keys that start with capital letters, where Grasscutter expects lower case.
Compare with https://github.com/Grasscutters/Grasscutter/blob/development/src/main/java/emu/grasscutter/data/excels/world/WorldAreaData.java
Doing this change fixed statues in Liyue and Inazuma. Sumeru's statues don't give you the choice to interact with them.
=> [BUGFIX] fix broken element changes at statues.

src/main/java/emu/grasscutter/scripts/ScriptLibHandler.java, src/main/java/emu/grasscutter/scripts/scriptlib_handlers/entities/GroupGadgetHandler.java
Sometimes, groupId is 0. That means you use the current group. We have a function to make that easy to do!
Fixes group 166001305
before:
after:
=> Use getGroupIdOrCurrentId when possible

src/main/java/emu/grasscutter/game/quest/GameMainQuest.java, src/main/java/emu/grasscutter/game/quest/GameQuest.java, src/main/java/emu/grasscutter/game/quest/QuestManager.java, src/main/java/emu/grasscutter/game/quest/QuestSystem.java
Quests that have isRewind=False cannot be rewind
Targets checkAndUpdateContent saves the quest if Content changed 
Don't modify finishProgressList if it's from a login
Fixes Prologue act 1 not finishing if you relogged while doing the dungeons.
=> Change way that finishProgressList is handled at login

src/main/java/emu/grasscutter/GameConstants.java, src/main/java/emu/grasscutter/data/binout/AbilityModifier.java, src/main/java/emu/grasscutter/game/ability/AbilityManager.java, src/main/java/emu/grasscutter/game/ability/actions/ActionExecuteGadgetLua.java, src/main/java/emu/grasscutter/game/ability/actions/ActionServerLuaCall.java, src/main/java/emu/grasscutter/game/ability/actions/ActionServerLuaTriggerEvent.java, src/main/java/emu/grasscutter/scripts/SceneScriptManager.java, src/main/java/emu/grasscutter/scripts/lua_engine/GroupEventLuaContext.java, src/main/java/emu/grasscutter/scripts/scriptlib_handlers/BaseHandler.java, src/main/java/emu/grasscutter/server/game/GameSession.java
GameConstants.java -> 
"Avatar_Trampoline_Jump_Controller" is needed to make bouncy mushrooms work. 
Added other things in the same area. Let me know if that is unwise.
AbilityModifier.java ->
Added luaCallType and funcName so I can use those in ActionServerLuaCall.
Changed params to DynamicFloat.
AbilityManager.java ->
Handled a nurupo that protoString was making.
Added modChange printing for flavor.
ActionExecuteGadgetLua.java ->
When it can't owner, make it target instead. More research is gonna happen tomorrow.
ActionServerLuaCall.java -> 
calls lua functions from the ability bin data.
There's a few more besides "FromGroup", but FromGroup is the easiest and most common.
GroupEventLuaContext.java ->
context.target_entity_id and context.source_entity_id happens from time to time. This …
=> Small Ability Fixes

src/main/java/emu/grasscutter/data/ResourceLoader.java, src/main/java/emu/grasscutter/data/common/quest/MainQuestData.java, src/main/java/emu/grasscutter/game/entity/EntityTeam.java, src/main/java/emu/grasscutter/game/managers/blossom/BlossomSchedule.java, src/main/java/emu/grasscutter/game/player/PlayerProgressManager.java, src/main/java/emu/grasscutter/game/quest/GameMainQuest.java, src/main/java/emu/grasscutter/game/quest/GameQuest.java, src/main/java/emu/grasscutter/game/quest/QuestManager.java, src/main/java/emu/grasscutter/game/quest/QuestSystem.java, src/main/java/emu/grasscutter/game/quest/content/ContentUnknown.java, src/main/java/emu/grasscutter/game/world/Scene.java
　　 ∧＿∧
　　（　´∀｀）＜ ぬるぽ
When trying 5.3, I was getting I lot of null pointer exceptions because the 5.3 questing resources are missing quite a few fields that grasscutter expects to be there, but blank.
Side bugs that are coming along for the ride:
ResourceLoader:
`GameData.getMonsterConfigData()` should be `targetMap` here in order for the print to give accurate data.
Scene:
When groups load, it's useful to know which groups loaded, not just how many.
=> null checks

src/main/java/emu/grasscutter/game/ability/AbilityManager.java, src/main/java/emu/grasscutter/game/quest/QuestManager.java, src/main/java/emu/grasscutter/game/quest/QuestSystem.java, src/main/java/emu/grasscutter/scripts/SceneScriptManager.java
Currently, when a quest condition or event is triggered, if there's some uncaught exception, the server just ignore it without logging out any useful error message.
I stumbled upon it when I tried Kaeya domain (main quest 307). Trial character (Kaeya) is not added.
I noticed some of the packets were missing, so after debugging I found out that this was silently failed:
```java
QuestManager.eventExecutor.submit(() -> {
if (!handler.execute(quest, execParam, params)) {
getLogger().debug("exec trigger failed {} at {}", execParam.getType().getValue(), quest.getQuestData());
}
});
```
With this fix, it will print out the error along with the stack trace, which is useful to know what went wrong. I also fix it for script and ability system.
(This error below is caused by missing `GrantReason` …
=> Fix: `eventExecutor` should log error instead of sliently fail

src/main/java/emu/grasscutter/data/binout/AbilityModifier.java, src/main/java/emu/grasscutter/game/ability/actions/ActionChangeTag.java, src/main/java/emu/grasscutter/game/entity/EntityAvatar.java, src/main/java/emu/grasscutter/game/entity/EntityClientGadget.java, src/main/java/emu/grasscutter/game/entity/EntityGadget.java, src/main/java/emu/grasscutter/game/entity/EntityItem.java, src/main/java/emu/grasscutter/game/entity/EntityMonster.java, src/main/java/emu/grasscutter/game/entity/EntityNPC.java, src/main/java/emu/grasscutter/game/entity/EntityVehicle.java, src/main/java/emu/grasscutter/game/entity/GameEntity.java, src/main/java/emu/grasscutter/server/packet/send/PacketEntityTagChangeNotify.java
Unsure what entity tags do.
This solves no known bugs.
ChangeTag happens when picking up an Electrogranum, but this change did not change broken behavior. 
As discussed before, I'm committing this instead of shelving it.
It might be a good idea to store EntityTag information on the entity in the server too?
=> Framework for EntityTag

src/main/java/emu/grasscutter/data/GameData.java, src/main/java/emu/grasscutter/data/ResourceLoader.java, src/main/java/emu/grasscutter/data/custom/activity/ActivityExtraInfo.java, src/main/java/emu/grasscutter/game/activity/ActivityConfigItem.java, src/main/java/emu/grasscutter/game/activity/ActivityHandler.java, src/main/java/emu/grasscutter/game/activity/ActivityManager.java, src/main/java/emu/grasscutter/game/activity/DefaultActivityHandler.java, src/main/java/emu/grasscutter/game/activity/PlayerActivityData.java, src/main/java/emu/grasscutter/game/activity/aster/AsterActivityHandler.java, src/main/java/emu/grasscutter/game/activity/aster/AsterGamePlayerData.java, src/main/java/emu/grasscutter/game/activity/irodori/IrodoriActivityHandler.java, src/main/java/emu/grasscutter/game/activity/musicgame/MusicGameActivityHandler.java, src/main/java/emu/grasscutter/game/activity/trialavatar/TrialAvatarActivityHandler.java, src/main/java/emu/grasscutter/game/inventory/Inventory.java, src/main/java/emu/grasscutter/game/player/Player.java, src/main/java/emu/grasscutter/game/quest/QuestManager.java, src/main/java/emu/grasscutter/game/world/Scene.java, src/main/java/emu/grasscutter/scripts/SceneScriptManager.java, src/main/java/emu/grasscutter/server/packet/recv/HandlerMusicGameStartReq.java
* Load "Server/ActivityExtraInfo.json" from the resources to get default dynamic groups to load
* This should help with getting some of the 1.x activities working
* Load all activity Activity Groups in scene Manager
* Fix wrong second parameter for the MusicGameStartReq
* Added the ability to register to the Inventory as VirtualCurrencyHandler
* This allows Activity Handlers like AsterActivityHandler to register for handling like aster credit and tokens
=> [Feature] Proper activity group loading and activity currency handling

src/main/java/emu/grasscutter/game/quest/enums/QuestExec.java, src/main/java/emu/grasscutter/game/quest/exec/ExecSetIsFlyable.java
If you don't start with the glider unlocked, you get softlocked at this point in the prologue:
This PR adds the exec that gives you the glider on this quest.
if you didn't have the glider, this gives you the glider on the quest that gives you the glider.
=> [Feature] QUEST EXEC SET IS FLYABLE

src/main/java/emu/grasscutter/game/quest/enums/QuestExec.java, src/main/java/emu/grasscutter/game/quest/exec/ExecRefreshGroupSuiteRandom.java
In quest 2001903, the monsters are not spawning:
This is a QUEST_EXEC_REFRESH_GROUP_SUITE_RANDOM.
setting it to load any one of the suites it specifies results in monsters, torches, crates, and gadgets:
This allows suites specified by QUEST_EXEC_REFRESH_GROUP_SUITE_RANDOM to be loaded. This is only done in dailies.
=> [Feature] QUEST EXEC REFRESH GROUP SUITE RANDOM

src/main/java/emu/grasscutter/game/inventory/Inventory.java, src/main/java/emu/grasscutter/game/quest/enums/QuestExec.java, src/main/java/emu/grasscutter/game/quest/exec/ExecDelAllSpecificPackItem.java, src/main/java/emu/grasscutter/game/quest/exec/ExecDelPackItem.java, src/main/java/emu/grasscutter/game/quest/exec/ExecDelPackItemBatch.java
+[Bugfix] removeItem -> removeItemById
+[Refactor] clean up removeItem() functions
When starting quest 2001903, it ought to remove item 100302 using a QUEST_EXEC_DEL_ALL_SPECIFIC_PACK_ITEM:
if not removed, this item causes the quest to instafinish.
Also included on this PR:
`ExecDelPackItem` and `ExecDelPackItemBatch` were using `removeItem` instead of `removeItemById`
removeItem uses guids, which are not the same thing as itemIds.
see https://github.com/Grasscutters/Grasscutter/commit/13f055035fc3584eb527c1f73148953103cdb392
Removed the null check out of `removeItem(long guid, int count)`. 
This null check happens immediately in `removeItem(GameItem item, int count)`
`removeItem(long guid)` now removes every item instead of one item in order to mach the other variations of this function. …
=> [Feature] QUEST EXEC DEL ALL SPECIFIC PACK ITEM

src/main/java/emu/grasscutter/game/quest/GameMainQuest.java, src/main/java/emu/grasscutter/game/quest/enums/QuestExec.java, src/main/java/emu/grasscutter/game/quest/exec/ExecUpdateParentQuestRewardIndex.java
QUEST_EXEC_UPDATE_PARENT_QUEST_REWARD_INDEX sets which reward happens at the end of a main quest.
Before, you would get every possible reward:
After, you now get one reward (default 0):
=> [Feature] QUEST EXEC UPDATE PARENT QUEST REWARD INDEX

src/main/java/emu/grasscutter/game/avatar/Avatar.java, src/main/java/emu/grasscutter/game/quest/enums/QuestExec.java, src/main/java/emu/grasscutter/game/quest/exec/ExecChangeSkillDepot.java
During quest 200102, it is supposed to take your element away. We didn't have that implemented:
Now it's in:
To do this, `changeElement` was split into `changeElement` and `changeSkillDepot`
See QUEST_EXEC_CHANGE_AVATAR_ELEMET (sic) for changing the avatar element by element Id (only used in first starting quest to give you the element when touching the statue for the first time)
=> [Feature] QUEST EXEC CHANGE SKILL DEPOT

src/main/java/emu/grasscutter/game/managers/giving/GivingManager.java, src/main/java/emu/grasscutter/game/quest/conditions/ConditionItemGivingFinished.java, src/main/java/emu/grasscutter/game/quest/conditions/ConditionPlayerEnterRegion.java, src/main/java/emu/grasscutter/scripts/SceneScriptManager.java
I forgot, but QUEST_COND are checked against the current game state. They are not checked against params[].
Both of these have been lightly tested as working.
=> [Refactoring] Quest conditions are not done by checking params[]

src/main/java/emu/grasscutter/game/inventory/Inventory.java, src/main/java/emu/grasscutter/game/quest/conditions/ConditionPackHaveItem.java, src/main/java/emu/grasscutter/game/quest/enums/QuestCond.java
Somehow, PACK_HAVE_ITEM and ITEM_NUM_LESS_THAN don't have things that trigger them.
This is important for quest 7218301: The Art of Horticulture
This quest is started only after obtaining the quest variant of [Naku Weed Seed](https://genshin-impact.fandom.com/wiki/Naku_Weed_Seed_(Quest_Item))
With these changes, the quest has started when I give myself that item:
=> [Feature] Triggers for PACK_HAVE_ITEM and ITEM_NUM_LESS_THAN

src/main/java/emu/grasscutter/data/excels/GatherData.java, src/main/java/emu/grasscutter/game/entity/EntityBaseGadget.java, src/main/java/emu/grasscutter/game/entity/create_config/CreateGadgetEntityConfig.java, src/main/java/emu/grasscutter/game/entity/gadget/content/GadgetGatherObject.java, src/main/java/emu/grasscutter/game/entity/gadget/content/GadgetGatherPoint.java
Some gadget is not interactable by default, it's defined in optional field `initDisableInteract` from `ExcelBinOutput/GatherExcelConfigData.json`
With this fix, Dandelion, Flaming Flowers and Mist Flowers can only be gathered after being hit by the right element.
=> Make flowers (Dandelion, FlamingFlower, MistFlower) not interactable by default

src/main/java/emu/grasscutter/game/entity/EntityRegion.java, src/main/java/emu/grasscutter/scripts/SceneScriptManager.java
Entities spawning inside of regions caused the regions to trigger. This was particularly bad in the chasm where paimon give some tips about babbling rocks. the region is in group 166001385, and it is triggered by a mushroom in group 166001308.
There are other affected groups. groups where you are supposed to follow a trail of gadgets, but the regions centered on those gadgets are triggered by the gadgets!
The old definitions of leaving and entering a region used to roughly be:
If something is inside a region and it had not been marked as inside the region in the previous tick, trigger enter region.
If something was marked as inside a region and now is outside the region, trigger leave region.
As an edge case, this triggered enter region when an entity spawns inside a region, or a region …
=> Make region entering/leaving symmetrical

src/main/java/emu/grasscutter/game/player/Player.java
Currently, we have the following packets sent:
- PlayerPropNotify (level up)
- PlayerPropChangeNotify (level up)
- PlayerPropNotify (exp)
- PlayerPropChangeNotify (exp)
- PlayerPropChangeReasonNotify (exp, PROP_CHANGE_REASON_PLAYER_ADD_EXP)
The correct packet order should be:
- PlayerPropNotify (level up)
- PlayerPropChangeReasonNotify (level up, PROP_CHANGE_REASON_PLAYER_ADD_EXP)
- PlayerPropNotify (exp)
- PlayerPropChangeReasonNotify (exp, PROP_CHANGE_REASON_AVATAR_UPGRADE)
I also checked v3.2, `PlayerPropChangeNotify` (cmd 139) doesn't show up anywhere, seems like PlayerPropNotify is enough.
v5.7 also doesn't make use of that. So sending it for "delta" in GC (sometimes negative like this) is unnecessary
Fix #200 
https://github.com/user-attachments/assets/83690502-ea59-4d0d-a4f9-cc4f05f …
=> Fix display EXP when Adventure Rank goes up
